name: 'Matrix Action'
description: 'Post build status to matrix server'
inputs:
  server:
    description: 'Matrix server'
    required: true
  room_id:
    description: 'Matrix room id'
    required: true
  token:
    description: 'Matrix access token'
    required: true
  status:
    description: 'Github build status'
    required: true
  github_token:
    description: 'Github job token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'